### ISSUE TITLE
number of classes during training

### ISSUE THREAD

**Issue by uhseon** [bl0/negative-margin.few-shot#13]
Hi! Thank you for your great work and sharing all codes.

For experiments on the CUB dataset, you set the number of output of linear classifier to 200 during training stage.
So, when using the neg-cosine loss, the number of weights W is 200, which is different from the Eq. (1) in p.4 of your paper.

During training stage, I think that the number of classes should be 100 as same as the number of base classes.
The weights corresponding to the classes which are base classes also used to computing the loss and gradients.

I'm not sure that this have meaningful positive or negative effects on the performances.
It would be very helpful if you let me know why you set the number of classes to 200. 

p.s. Since I'm very new to few-shot learning task so I might misunderstand. Then, please understand in advance.

Best,
Seon.

**Comment by bl0** [comment]
Hi,  Thanks for your attention to our works.

This doesn't affect the final performance. It just wastes a little memory and training time.
The base classes are randomly sampled from CUB, so the maximum class id is larger than 100. For simplicity, we set FC nodes to 200 instead of remapping the class id into the range of 0 to 99.
BTW, this trick is firstly introduced by [closer look](https://github.com/wyharveychen/CloserLookFewShot/blob/e03aca8a2d01c9b5861a5a816cd5d3fdfc47cd45/io_utils.py#L28), we just follow their setting.

Best,
Bin

**Comment by uhseon** [comment]
Thanks!
